version: '3.8'

# change razmga everywhere
services:
  razmga:
    build: 
      context: ./razmga
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./razmga/:/usr/src/app/
    ports:
      - 8000:8000
